version: 2.1
orbs:
  node: circleci/node@4
  codecov: codecov/codecov@1
jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: test
          command: yarn test:ci
      - run:
          name: lint
          command: yarn lint
  release:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          context:
            - npm
          filters:
            branches:
              only:
                - master
          requires:
            - test
